- name: Search for CONFIG_MODULE_SIG
        run: |
          echo "=== ПОШУК УСІХ ЗГАДОК CONFIG_MODULE_SIG ==="
          # -r: рекурсивний пошук
          # -n: показати номер рядка
          # -w: шукати ціле слово
          grep -rnw . -e "CONFIG_MODULE_SIG" | grep -v ".git/"
